/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CPO;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Osvaldo Bosquez
 */
public class ComponenteCampoTectoObligatorio extends javax.swing.JPanel {

    private Border border = BorderFactory.createLineBorder(Color.red);
    private Border bordeb = BorderFactory.createLineBorder(Color.black);
    /**
     * Creates new form ComponenteCampoTectoObligatorio
     */
    public ComponenteCampoTectoObligatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtObligatorio = new javax.swing.JTextField();
        lblObligatorio = new javax.swing.JLabel();

        txtObligatorio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObligatorioFocusLost(evt);
            }
        });

        lblObligatorio.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtObligatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblObligatorio))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtObligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblObligatorio)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtObligatorioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObligatorioFocusLost
       if(txtObligatorio.getText().isEmpty()){
            txtObligatorio.setBorder(border);
            lblObligatorio.setForeground(Color.red);
        }else if(!txtObligatorio.getText().isEmpty()){
            txtObligatorio.setBorder(bordeb);
            lblObligatorio.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtObligatorioFocusLost

    public void evaluar(){
        txtObligatorioFocusLost(null);
    }
    public void setText(String text){
        txtObligatorio.setText(text);
        evaluar();
    }
    public String getText(){
        return txtObligatorio.getText();
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblObligatorio;
    private javax.swing.JTextField txtObligatorio;
    // End of variables declaration//GEN-END:variables
}
